pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                // Get code from a GitHub repository
                git url: 'https://github.com/bathrinath2021/jenkin-pipe.git', branch: 'main'
				}
				}
				}
				}
